
version: '3'

services:
  db:
    container_name: database
    image: postgres:alpine
    volumes:
      - ./docker/db:/var/lib/postgresql/data
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/api
    depends_on:
          - db

  frontend:
    container_name: frontend
    image: node:lts-alpine
    working_dir: /home/myproject/front
    volumes:
      - ./frontend:/home/myproject/front
    ports:
      - "7000:3000"
    command: ["yarn", "start"]
