
#Signup

POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "ash",
  "email":"ash2@email.com",
  "password":"foobar",
  "password_confirmation":"foobar"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ash@email.com",
  "password": "foobar"
}

###

GET http://localhost:3000/auth/login
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NjM1NzA3MTh9.HfVBwb-zRbRLJTiWf94YhY0CD6kPjBj3hnVUuUPWj0Y

###

# GET /todos
GET http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NjE2NTAyNjV9.rarcScfCOpSz1A8gAe_sX2Zp8Rof7SpOhJAjc8BEJ1g

###

# POST /todos
POST http://localhost:3000/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NjE2NTAyNjV9.rarcScfCOpSz1A8gAe_sX2Zp8Rof7SpOhJAjc8BEJ1g

{
  "title": "Mozart",
  "created_by": 1
}

###

# PUT /todos/:id
PUT http://localhost:3000/todos/1
Content-Type: application/json

{
  "title": "Beethoven"
}

###

GET http://localhost:3000/feed
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NjM2MDA1NjZ9.Gn57ROOk7WEdaZLtOxzilAbMMhgjWP43ZbUSRHJewZw

###

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NjM2MDA1NjZ9.Gn57ROOk7WEdaZLtOxzilAbMMhgjWP43ZbUSRHJewZw

{
  "text": "test post",
  "name": "test post",
  "user_id": 1
}

###

POST http://localhost:3000/posts/1/comments
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NjM2MDA1NjZ9.Gn57ROOk7WEdaZLtOxzilAbMMhgjWP43ZbUSRHJewZw

{
  "text": "test comment",
  "name": "test comment",
  "user_id": 1,
  "post_id": 1
}

###


GET http://localhost:3000/posts/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NjM2MDA1NjZ9.Gn57ROOk7WEdaZLtOxzilAbMMhgjWP43ZbUSRHJewZw

###

# DELETE /todos/:id
DELETE http://localhost:3000/todos/1

# GET /todos/:todo_id/items
$ http :3000/todos/2/items
# POST /todos/:todo_id/items
$ http POST :3000/todos/2/items name='Listen to 5th Symphony' done=false
# PUT /todos/:todo_id/items/:id
$ http PUT :3000/todos/2/items/1 done=true
# DELETE /todos/:todo_id/items/1
$ http DELETE :3000/todos/2/items/1
